# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-18 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fakedataapp', '0002_auto_20190818_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faked1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FakeData',
        ),
    ]
