# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-22 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durgasoftapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesdata',
            name='course_start_date',
            field=models.DateField(max_length=100),
        ),
    ]
