# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-22 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durgasoftapp1', '0002_auto_20190822_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicesData',
            new_name='ServicesData1',
        ),
    ]
