# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=100)),
                ('elocation', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edesignation', models.CharField(max_length=100)),
                ('esalary', models.IntegerField()),
                ('abc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empapp.emp')),
            ],
        ),
    ]
