# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otooapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1',
            name='abc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='otooapp.student1'),
        ),
    ]
