# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otooapp', '0002_auto_20190805_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otooapp.student1'),
        ),
    ]
