# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otooapp', '0003_auto_20190805_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=models.SET(3), to='otooapp.student1'),
        ),
    ]
