# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mtoapp.Student'),
        ),
    ]
