# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-06 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtoapp', '0002_auto_20190806_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=models.SET(3), to='mtoapp.Student'),
        ),
    ]
