# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-06 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtoapp', '0003_auto_20190806_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mtoapp.Student'),
        ),
    ]
