# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-23 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htnlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custdata',
            old_name='sales',
            new_name='num',
        ),
    ]
