# Generated by Django 2.1 on 2019-09-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_class', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=100)),
                ('product_cost', models.IntegerField()),
            ],
        ),
    ]
